### ISSUE TITLE
[Bug]: Unable to unsubscribe to remote communities stuck in the Subscribe Pending state

### ISSUE THREAD

**Issue by IanNorris** [LemmyNet/lemmy-ui#1315]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Summary

If you subscribe to a community you no longer want to subscribe to, if the subscription is stuck in a pending state (Subscribe Pending) then there is no way to unsubscribe from it. Clicking the link in the UI does nothing.

This probably happens at the moment if some instances are backed up. I have multiple in this state, for example memes@lemmy.ml without any way to unsubscribe.

### Steps to Reproduce

1. Subscribe to a community on a congested instance (eg memes@lemmy.ml) 
2. Go to the Communities list and click to show your Subscribed list. 
3. Observe the Subscription Pending state
4. Notice there is no way to cancel the pending subscription even though the content appears in the feed

### Technical Details

N/A

### Version

0.17.4, 0.18.0

### Lemmy Instance URL

Lemmy.world

**Comment by alectrocute** [comment]
@SleeplessOne1917 This is fixed in >= 0.18, yeah?

**Comment by SleeplessOne1917** [comment]
@alectrocute I'm not entirely sure. If you want to verify, you can test on voyager.lemmy.ml, which is currently running 0.18.

**Comment by IanNorris** [comment]
Would I be right in thinking voyager is unfederated? From what I can tell it can't see other instances. I think the issue may have been made visible by lemmy.world being unfederated from beehaw and lemmy.ml which were the instances stuck in the Subscribe Pending state for me.

**Comment by SleeplessOne1917** [comment]
@IanNorris voyager is not federated.

**Comment by IanNorris** [comment]
Unfortunately I can confirm that 0.18.0 doesn't fix the issue.

**Comment by Gestrid** [comment]
Can confirm. My instance, lemmy.ca, is on 0.18.0, and it's still happening. Notably, it's only happening to communities that I sub to on lemmy.ml, though the other instances I sub to probably aren't nearly as busy as that one.

**Comment by zacharee** [comment]
lemmy.ml works for me from sh.itjust.works, but lemmy.world and zerobytes.monster are stuck in the pending state. Posts in the communities I'm trying to subscribe to don't federate to my instance, either, so I don't think it's just an issue with the response to the request.

**Comment by Nutomic** [comment]
This has been fixed, clicking the yellow button with "subscription pending" results in unsubscribe.
